const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const context=vm.createContext({console,Math,Set,Map,Float32Array,Int32Array,Uint8Array,Infinity,assert,sfx(){},announce(){},killFeed(){},speak(){}});
for(const file of ['riot-data','data','champions','rift-map','rift-grid','engine','rift-terrain','rift-game'])vm.runInContext(fs.readFileSync(`js/${file}.js`,'utf8'),context,{filename:file+'.js'});
vm.runInContext(`
let tests=0;
function check(name,fn){fn();tests++;console.log('PASS',name);}
function arena(id){const g=new Game(id,{mode:'practice'});g.nav=null;g.monsters=[];g.towers=[];g.inhibs=[];g.nexuses=[];g.wards=[];g._unitsCacheT=-1;g.player.x=3000;g.player.y=3500;g.player.focus=4;g.player.annieStack=4;g.player.order={type:'stop'};for(let i=1;i<g.champs.length;i++){const u=g.champs[i];u.x=i===4?3200:3150+(i-1)*50;u.y=3500;u.maxHp=20000;u.hp=20000;u.visBlue=u.visRed=true;}g.practiceReveal=true;return g;}
function tick(g,seconds){for(let i=0;i<Math.ceil(seconds/.025);i++)g.update(.025);}
check('ten unique real champions and fifty local skill assets',()=>{assert.equal(CHAMPIONS.length,10);assert.equal(new Set(CHAMPIONS.map(c=>c.id)).size,10);assert.equal(CHAMP_BY_ID.ahri.name,'阿狸');for(const c of CHAMPIONS){assert.equal(c.abilities.length,4);assert(c.portrait&&c.passiveIcon);}});
check('all forty spells execute and advance simulation',()=>{for(const c of CHAMPIONS)for(let i=0;i<4;i++){const g=arena(c.id),p=g.player,a=p.abilities[i],target=a.def.aim==='ally'?g.champs[4]:g.champs[1];if(a.def.aim==='ally')target.hp=100;const success=p.castAbility(g,i,{x:target.x,y:target.y,unit:target});assert(success,c.id+' '+a.def.key);tick(g,2);for(const u of g.units())assert(Number.isFinite(u.hp)&&Number.isFinite(u.x)&&Number.isFinite(u.y),c.id+' invalid unit');}});
check('Garen ultimate deals true damage through armor and reduction',()=>{const g=arena('garen'),u=g.champs[1];u.hp=u.maxHp=2000;addBuff(u,{id:'testDR',dur:3,stats:{dr:90}});const hp=u.hp;g.player.castAbility(g,3,{unit:u});assert.equal(hp-u.hp,450);});
check('Annie empowered cone stuns every target once and resets stacks',()=>{const g=arena('annie'),p=g.player;p.castAbility(g,1,{x:3400,y:3500});assert(g.champs[1].isStunned());assert(g.champs[2].isStunned());assert.equal(p.annieStack,0);});
check('Annie Q kill refunds mana, R creates persistent Tibbers',()=>{const g=arena('annie'),p=g.player;g.champs[1].hp=1;const mana=p.mp;p.castAbility(g,0,{unit:g.champs[1]});tick(g,.3);assert.equal(p.mp,mana);p.castAbility(g,3,{x:3150,y:3500});assert.equal(g.pets.length,1);assert.equal(g.pets[0].kind,'tibbers');tick(g,1);assert(!g.pets[0].dead);});
check('Lux E has a mana-free detonation recast',()=>{const g=arena('lux'),p=g.player,u=g.champs[1];p.castAbility(g,2,{x:u.x,y:u.y});tick(g,.15);const mana=p.mp,cd=p.abilities[2].readyAt;assert(p.castAbility(g,2,{x:0,y:0}));assert.equal(p.mp,mana);assert.equal(p.abilities[2].readyAt,cd);tick(g,.1);assert(u.hp<20000);assert(!p.luxZone);assert(u.hasBuff('illumination'+p.id));});
check('Ahri orb hits once outward and once returning',()=>{const g=arena('ahri'),p=g.player,u=g.champs[1];const hp=u.hp;p.castAbility(g,0,{x:3500,y:3500});tick(g,.35);const first=hp-u.hp;assert(first>0);tick(g,1);assert(hp-u.hp>first*1.8);});
check('Ahri ultimate offers exactly three charges without extra mana',()=>{const g=arena('ahri'),p=g.player;p.castAbility(g,3,{x:3000,y:3300});const mana=p.mp;tick(g,1.1);assert(p.castAbility(g,3,{x:3000,y:3500}));tick(g,1.1);assert(p.castAbility(g,3,{x:3000,y:3300}));assert.equal(p.ahriDashes,0);assert(!p.castAbility(g,3,{x:3000,y:3300}));assert(p.mp>=mana);});
check('Ashe Q requires four focus stacks',()=>{const g=arena('ashe'),p=g.player;p.focus=0;assert(!p.castAbility(g,0,{}));for(let i=0;i<4;i++)p.def.aaOnHit(g,p,g.champs[1]);assert(p.castAbility(g,0,{}));assert.equal(p.focus,0);assert(p.hasBuff('asheQ'));});
check('skillshot hits the closest blocker even when unit storage order is reversed',()=>{const g=arena('ashe'),p=g.player,near=g.champs[1],far=g.champs[2];near.x=3100;far.x=3140;g.champs=[p,far,near];g._unitsCacheT=-1;const hits=[];spawnProj(g,{x:3000,y:3500,dir:0,speed:2000,maxDist:600,r:5,team:'blue',onHit:(g,u)=>hits.push(u.id)});updateProjectiles(g,.1);assert.deepEqual(hits,[near.id]);});
check('Caitlyn ultimate deals damage to an intercepting champion and can be cancelled',()=>{const g=arena('caitlyn'),p=g.player,target=g.champs[2],block=g.champs[1];target.x=3450;block.x=3200;g.champs=[p,target,block];g._unitsCacheT=-1;assert(p.castAbility(g,3,{unit:target}));tick(g,1.5);assert(block.hp<20000);assert.equal(target.hp,20000);const h=arena('caitlyn');h.player.castAbility(h,3,{unit:h.champs[1]});addBuff(h.player,{id:'interrupt',dur:2,stun:true});tick(h,1.5);assert.equal(h.champs[1].hp,20000);});
check('Darius five-stack execute opens a free recast and empowered bleed',()=>{const g=arena('darius'),p=g.player,u=g.champs[1];for(let i=0;i<5;i++)hemorrhage(g,p,u);assert.equal(u.buffs.find(b=>b.id==='bleed'+p.id).stacks,5);assert(p.hasBuff('noxianMight'));u.hp=1;assert(p.castAbility(g,3,{unit:u}));assert(u.dead);assert(p.abilityReady(3));const mana=p.mp;g.champs[2].x=3160;assert(p.castAbility(g,3,{unit:g.champs[2]}));assert.equal(p.mp,mana);assert(!p.abilityReady(3));});
check('Caitlyn traps arm then root enemy champions',()=>{const g=arena('caitlyn'),p=g.player,u=g.champs[1];p.castAbility(g,1,{x:u.x,y:u.y});tick(g,.5);assert(!u.isRooted());tick(g,.7);assert(u.isRooted());assert(u.hasBuff('caitMark'+p.id));});
check('Soraka cannot heal herself with W and pays health for allies',()=>{const g=arena('soraka'),p=g.player,u=g.champs[4];u.hp=100;assert(!p.castAbility(g,1,{unit:p}));const hp=p.hp;assert(p.castAbility(g,1,{unit:u}));assert(p.hp<hp);assert(u.hp>100);});
check('Master Yi Q ends untargetability, E adds true damage',()=>{const g=arena('yi'),p=g.player;p.castAbility(g,0,{unit:g.champs[1]});assert(p.untargetable);tick(g,1);assert(!p.untargetable);p.castAbility(g,2,{});assert(p.buffs.some(b=>b.trueOnHit));});
check('silence, pause and invalid targets prevent resource spending',()=>{const g=arena('lux'),p=g.player;const mana=p.mp;addBuff(p,{id:'silence',dur:1,silence:true});assert(!p.castAbility(g,0,{x:3300,y:3500}));assert.equal(p.mp,mana);p.buffs=[];g.paused=true;assert(!p.castAbility(g,0,{x:3300,y:3500}));assert(!p.castSumm(g,0,{x:3300,y:3500}));g.update(2);assert.equal(g.t,0);});
check('classic draft matches preview, structures and jungle spawn timers',()=>{const draft=createDraft('ashe','bot'),g=new Game('ashe',{lane:'bot'});assert.equal(g.champs.length,10);assert.equal(new Set(g.champs.map(c=>c.def.id)).size,10);assert.deepEqual(g.champs.filter(c=>c.team==='blue').map(c=>c.def.id),draft.blue.map(p=>p.def.id));assert.equal(g.towers.length,22);assert.equal(g.inhibs.length,6);assert.equal(g.monsters.length,16);assert(g.monsters.every(m=>m.dead));assert.equal(g.nextWaveAt,65);});
check('authentic grid keeps walls solid and every lane and camp reachable',()=>{const g=new Game('garen');assert.equal(GRID_CELLS.length,295*296);assert(!mapWalkable(NEXUS_POS.blue.x,NEXUS_POS.blue.y));for(const lane of Object.values(g.lanePaths)){let prev=FOUNTAIN_POS.blue;for(const p of lane){assert(mapWalkable(p.x,p.y,26));assert(g.nav.path(prev,p).length);prev=p;}}for(const camp of JUNGLE_CAMPS){assert(mapWalkable(camp.x,camp.y,20),'camp blocked '+camp.kind);assert(g.nav.path(FOUNTAIN_POS.blue,camp).length,'camp unreachable '+camp.kind);}});
check('minion separation never pushes a unit into a navgrid wall',()=>{const g=new Game('garen');const p=g.lanePaths.mid[3];let edge;for(let y=p.y-200;y<p.y+200&&!edge;y+=5)for(let x=p.x-200;x<p.x+200;x+=5){if(mapWalkable(x,y,13)&&!mapWalkable(x-5,y,13)){edge={x,y};break;}}assert(edge);const a=new Minion(g,'melee','blue','mid'),b=new Minion(g,'melee','blue','mid');Object.assign(a,edge);Object.assign(b,{x:edge.x+4,y:edge.y});g.minions=[a,b];const original={x:a.x,y:a.y};g.separateMinions();assert(mapWalkable(a.x,a.y,a.radius));assert(a.x>=original.x);});
check('authentic brush conceals enemies outside its connected patch',()=>{const g=arena('garen');g.practiceReveal=false;g.champs=g.champs.slice(0,2);const k=GRID_CELLS.findIndex(f=>f===1),p={x:(k%RIFT_GRID.width+.5)*WORLD/RIFT_GRID.width,y:(Math.floor(k/RIFT_GRID.width)+.5)*WORLD/RIFT_GRID.height},enemy=g.champs[1];Object.assign(enemy,p);let outside;for(let a=0;a<Math.PI*2;a+=.1){const q={x:p.x+Math.cos(a)*180,y:p.y+Math.sin(a)*180};if(brushAt(q)<0&&visionLineClear(p,q)){outside=q;break;}}assert(outside);Object.assign(g.player,outside);g._unitsCacheT=-1;g.computeVision();assert(!enemy.visBlue);Object.assign(g.player,p);g.nextVisionAt=0;g.computeVision();assert(enemy.visBlue);});
check('building progression and Nexus requires an active destroyed inhibitor',()=>{const g=new Game('garen');const tower=g.towers.find(t=>t.team==='red'&&t.lane==='mid'&&t.tier===2);assert(!tower.attackable);const hp=tower.hp;dealDamage(g,g.player,tower,999999,'true');assert.equal(tower.hp,hp);g.towers.find(t=>t.team==='red'&&t.lane==='mid'&&t.tier===1).dead=true;assert(tower.attackable);g.towers.filter(t=>t.team==='red'&&t.tier===4).forEach(t=>t.dead=true);const nexus=g.nexuses.find(n=>n.team==='red');assert(!nexus.attackable);g.inhibs.find(i=>i.team==='red').dead=true;assert(nexus.attackable);});
check('official item stats, component credits and six-slot boot upgrades',()=>{const g=arena('lux'),p=g.player;assert.equal(ITEM_BY_ID.rod.stats.ap,65);assert.equal(ITEM_BY_ID.sorcs.stats.magicPen,12);assert(!ITEM_BY_ID.sorcs.stats.ap);p.items=[ITEM_BY_ID.boots,ITEM_BY_ID.rod,ITEM_BY_ID.rod,ITEM_BY_ID.dring,ITEM_BY_ID.tome,ITEM_BY_ID.cloak];p.gold=10000;const gold=p.gold;assert.equal(purchaseItem(p,ITEM_BY_ID.sorcs),null);assert.equal(p.items.length,6);assert.equal(gold-p.gold,ITEM_BY_ID.sorcs.price-ITEM_BY_ID.boots.price);assert(purchaseItem(p,ITEM_BY_ID.mercury));const before=p.gold;assert.equal(purchaseItem(p,ITEM_BY_ID.rabadon),null);assert.equal(p.items.length,5);assert.equal(before-p.gold,ITEM_BY_ID.rabadon.price-2*ITEM_BY_ID.rod.price);p.items=[ITEM_BY_ID.bc];assert(Math.abs(p.stat('cdr')-100/6)<.0001);p.items=[ITEM_BY_ID.lsword];assert(itemPurchaseQuote(p,ITEM_BY_ID.bc).consumed.length===1);});
check('ten-minute AI simulation stays finite and advances all lanes',()=>{const g=new Game('ahri',{lane:'mid'});g.damageNumbers=false;for(let i=0;i<3600&&!g.over;i++)g.update(1/6);assert(g.t>=599||g.over);assert(g.waveNum>10);assert(g.minions.length>0);for(const c of g.champs)assert(Number.isFinite(c.x)&&Number.isFinite(c.hp));console.log('Simulation:',{time:g.t,waves:g.waveNum,kills:g.teamKills('blue')+g.teamKills('red'),minions:g.minions.length});});
console.log(tests+' regression tests passed');
`,context,{timeout:180000});
