"""Download pinned public Data Dragon assets. Run from any directory; no API key."""
import concurrent.futures
import hashlib
import json
from pathlib import Path
import time
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets' / 'riot'
VERSION = '14.24.1'
CDN = 'https://ddragon.leagueoflegends.com'
HEROES = ['Garen','Darius','Ashe','Caitlyn','Ahri','Lux','Annie','MasterYi','Malphite','Soraka']
ITEMS = [1055,1056,1054,1036,1038,1043,3031,3072,3071,3078,3087,1052,1058,3089,3157,6655,3116,1031,1057,3075,3143,3065,3083,1001,3006,3020,3047,3111]
manifest = []

def fetch(url, rel):
    path = OUT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    for attempt in range(3):
        try:
            data = path.read_bytes() if path.exists() else urllib.request.urlopen(url, timeout=35).read()
            path.write_bytes(data)
            manifest.append({'path':str(path.relative_to(ROOT)).replace('\\','/'), 'url':url, 'bytes':len(data), 'sha256':hashlib.sha256(data).hexdigest()})
            return data
        except Exception:
            if attempt == 2: raise
            time.sleep(attempt + 1)

def champion(name):
    data = json.loads(fetch(f'{CDN}/cdn/{VERSION}/data/zh_CN/champion/{name}.json', f'data/{name}.json'))['data'][name]
    jobs = [(f'{CDN}/cdn/{VERSION}/img/champion/{name}.png', f'champions/{name}.png'),
            (f'{CDN}/cdn/img/champion/splash/{name}_0.jpg', f'splash/{name}.jpg'),
            (f'{CDN}/cdn/{VERSION}/img/passive/{data["passive"]["image"]["full"]}', f'spells/{name}_P.png')]
    jobs += [(f'{CDN}/cdn/{VERSION}/img/spell/{spell["image"]["full"]}', f'spells/{name}_{key}.png') for key,spell in zip('QWER',data['spells'])]
    for url,path in jobs: fetch(url,path)
    return name,data

if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        champs = dict(pool.map(champion,HEROES))
        list(pool.map(lambda i:fetch(f'{CDN}/cdn/{VERSION}/img/item/{i}.png', f'items/{i}.png'), ITEMS))
    for name in ['SummonerFlash','SummonerHeal','SummonerSmite','TrinketTotemLvl1']:
        # Trinket uses item art.
        if name == 'TrinketTotemLvl1': continue
        fetch(f'{CDN}/cdn/{VERSION}/img/spell/{name}.png', f'spells/{name}.png')
    fetch(f'{CDN}/cdn/{VERSION}/img/map/map11.png','map/map11.png')
    items=json.loads(fetch(f'{CDN}/cdn/{VERSION}/data/zh_CN/item.json','data/items.json'))
    bundle={'version':VERSION,'champions':champs,'items':{str(i):items['data'][str(i)] for i in ITEMS},'recipes':{i:r.get('from',[]) for i,r in items['data'].items()}}
    (ROOT/'js'/'riot-data.js').write_text('/* Generated by scripts/fetch-riot-assets.py */\nconst RIOT_DATA = '+json.dumps(bundle,ensure_ascii=False)+';\n',encoding='utf-8')
    (OUT/'manifest.json').write_text(json.dumps({'version':VERSION,'sources':sorted(manifest,key=lambda a:a['path'])},ensure_ascii=False,indent=2),encoding='utf-8')
    print(f'Downloaded and verified {len(manifest)} assets; patch {VERSION}.')
